# fly.toml app configuration file generated for hooks on 2024-05-01T10:48:53-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hooks"
primary_region = "dfw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
